### ISSUE TITLE
allowlist type

### ISSUE THREAD

**Issue by annevk** [WICG/feature-policy#105]
allowlist is defined as a set of origins.

However, along with a set it apparently can also be *, "self", or "none". This should be stated upfront.

**Comment by clelland** [comment]
By 'set' I didn't mean an [ordered set](https://infra.spec.whatwg.org/#ordered-set), but a (possibly unbounded) collection of origins. This is why the serialization needs to allow `*`.

The serialization also uses `"none"` to denote the empty set, and `"self"` is shorthand to refer to the origin of the document itself, whatever that might be, but regardless of how it has to be typed out, an allowlist still just *is a* set, in the mathematical sense. Perhaps the term 'collection' would be better, but 'set' seemed nicely precise.

**Comment by annevk** [comment]
Well, given that we have a definition for "ordered set" and this doesn't fit, I'd disagree on this being precise.

What I think this should do is instead describe the internal data model. Which is likely that this is either a special value or an ordered set.

**Comment by clelland** [comment]
SGTM. The only special value, in the internal model, is *.

The other two are just syntax, and are resolved during parsing so that if the allowlist is not the set of all origins, then it's an ordered list of specific origins.

**Comment by annevk** [comment]
Okay, you might want to make sure that's the case, since I believe at least for "self" Chrome and Firefox have different behavior in CSP, to which you're now wedded. I haven't checked what the latest on that is though. Maybe @mikewest knows.

**Comment by annevk** [comment]
@clelland is https://github.com/WICG/feature-policy/issues/105#issuecomment-353099159 tracked somehow?

**Comment by annevk** [comment]
I guess it's implicitly tracked by the refactoring required of CSP to allow reuse?

**Comment by clelland** [comment]
It seemed wrong to re-open this issue for that comment; I was just opening #124 to track it separately
