### ISSUE TITLE
target: "self" doesn't help defend against XSS.

### ISSUE THREAD

**Issue by jyasskin** [WICG/feature-policy#12]
Imagine that a site wants to run relatively loosely-audited code on `origin.com`, but restrict code that uses permissions to `audited.origin.com`. The idea is that if `origin.com` gets XSS'ed, none of the site's permissions can be mis-used by the attacker. With the current [Feature Policy](https://igrigorik.github.io/feature-policy/) and [Permission Delegation](https://noncombatant.github.io/permission-delegation-api/) proposals, the site writes this like:

```
https://origin.com/index.html:
Feature-Policy: {"disable":["geolocation", "midi", "notifications", "push", "webrtc"], "target":"self"}

<iframe src="https://audited.origin.com/location_helper.html" permissions="geolocation"></iframe>
```

And `audited.origin.com/location_helper.html` would be careful to validate requests from its embedder to be "safe" in some way.

However, if `origin.com` gets XSS'ed, this doesn't help. The attacker can add a new `<iframe src="https://evil.com/attack.html" permissions="geolocation"></iframe>` element to the page, and get full access without a prompt.

I think we need a whitelist of enabled origins in the Feature Policy line, if we want it to help protect against XSSes.

**Comment by ojanvafai** [comment]
Is target:self meant to defend against XSS? I think it's more for incremental adoption than security, i.e. I want this on my first party content by I can't force some third party I embed to do this.

I think it'd be OK to say that target:cascade is not overrideable via the attribute though and that if you want the security assurance you should be using target:cascade.

Does that work?

**Comment by igrigorik** [comment]
> I think it'd be OK to say that target:cascade is not overrideable via the attribute though and that if you want the security assurance you should be using target:cascade.

This makes it impossible to whitelist a specific origin: either you block access for everyone, including yourself, or you keep it open for everyone... That said, perhaps https://github.com/igrigorik/feature-policy/issues/13 could address this?

--- 

Taking a step back.. *_If_* it is our goal is to address the XSS case (is it? :)), then I think we have to restrict ourselves to the header mechanism. Or, at least, if you want to protect yourself from the XSS case then: you _MUST_ use the header mechanism; the header mechanism needs to support a whitelisting mechanism (which is what the attribute provides); header policy must take precedence over the attribute values?

```
Feature-Policy: {"disable":["geolocation"], "target":["cascade"]}, 
           {"enable":["geolocation"], target:["https://foo.com"]}

<iframe src="https://foo.com/widget"> <!-- Geolocation enabled -->
<iframe src="https://bar.com/thing" enable="geolocation"> <!-- noop...? -->
```

**Comment by igrigorik** [comment]
@jyasskin I think @mikewest's update addresses this case. Can you review and confirm?

**Comment by jyasskin** [comment]
It's a step, but to protect against XSS we need a whitelist of origins, while {disable: 'thing', target: [evilx, evily, evilz]} still allows evilw to use 'thing'. When 'enable' rules exist, that'll finish addressing this case.

**Comment by jkarlin** [comment]
Was it necessary to throw "self" out? It would be very nice to have as it's much more copy&pasteable and useful for snippets:

```javascript
Feature-Policy: {"enable":["geolocation"], "target":["self"]}, {"disable":["geolocation"], "target":["!self"]}
```

**Comment by igrigorik** [comment]
I think we can add "self", but I don't think we want to get into predicates with "!self" and such. /cc @mikewest

**Comment by jkarlin** [comment]
Then I propose adding self and third-party as targets.

**Comment by igrigorik** [comment]
See discussion in https://github.com/WICG/feature-policy/issues/28#issuecomment-237385392.
