### ISSUE TITLE
Feature proposal: sync-xhr

### ISSUE THREAD

**Issue by clelland** [WICG/feature-policy#126]
Posting this here for completeness, there is a corresponding issue at https://github.com/whatwg/xhr/issues/178 for the XHR spec change.

The proposal is to add a new feature, `sync-xhr`, which is enabled by default (default allowlist is `*`)

When disabled, calling `send()` on an XMLHttpRequest object with the async flag set to false will cause a NetworkError exception to be thrown. (This is chosen to avoid adding a new failure path for existing code which makes use of synchronous XHR)

**Comment by RByers** [comment]
Anything left before calling this done?

**Comment by clelland** [comment]
Not for this issue, I suppose -- the PR is still out on https://github.com/whatwg/xhr/issues/178, waiting on the changes to be made to HTML before it lands, I believe.

**Comment by annevk** [comment]
I think I was happy to land https://github.com/whatwg/xhr/pull/177 provided implementation bugs were filed, but I see that in https://github.com/whatwg/xhr/pull/177/#issuecomment-352096769 you did note it depended on changes to HTML.

**Comment by RByers** [comment]
This has landed in the spec and shipped in Chrome. Can we just add it to [features.md](https://github.com/WICG/feature-policy/blob/master/features.md) and mark this as closed please? BTW is anything else missing from features.md?

**Comment by clelland** [comment]
Added.

features.md could use a few changes -- It uses a normative voice when it really shouldn't, and should probably, in most cases, just link directly to the relevant specs, now that those are starting to integrate with FP themselves.

Eventually all of that documentation should be moved somewhere like MDN, but features.md may need to stick around for a while to document the things that aren't really standards yet.
