### ISSUE TITLE
spec seems inconsistent about whether 'self' 'src' and 'none' require single quotes around them

### ISSUE THREAD

**Issue by dbaron** [WICG/feature-policy#147]
Many places in [the spec](https://wicg.github.io/feature-policy/) such as [2. examples](https://wicg.github.io/feature-policy/#examples) or [4.8. Allowlists](https://wicg.github.io/feature-policy/#allowlists) and [5.1. ASCII serialization](https://wicg.github.io/feature-policy/#ascii-serialization) seem to imply that the `'self'`, `'src'`, and `'none'` keywords have to have single quotes around them, but the formal algorithms in [8.3. Parse policy directive from value and origin](https://wicg.github.io/feature-policy/#parse-policy-directive) and [8.6. Parse allow attribute](https://wicg.github.io/feature-policy/#parse-allow-attribute) do not seem to require the quotes.

This seems inconsistent; I think these should agree.

**Comment by clelland** [comment]
Thanks -- the quotes are required, and are part of the values. That should get fixed.
