### ISSUE TITLE
Should we support `<meta http-equiv>` mechanism to set the policy?

### ISSUE THREAD

**Issue by igrigorik** [WICG/feature-policy#15]
From [current draft](http://igrigorik.github.io/feature-policy/#feature-policy-http-header-field):

> The policy must be delivered via an HTTP response header field to be processed by the client; the client must ignore any policy set via meta element's http-equiv attribute.
> > The feature policy needs to be set before the response is processed and before any subresource requests are initiated. Once active the policy also needs to apply for the lifetime of the document and is not allowed to be modified at runtime. Due to these requirements, meta element cannot be used to set the policy.

Origin-Trials folks, on the other hand, support `<meta>` mechanism and are worried that lack of such adds a barrier to adoption ("I can't emit a header, I host my thing on GitHub Pages, or some such"). 

Practically speaking, I guess we _could_ support meta, but we'd have to put a bunch of caveats:
 - It must come before any script is executed (is this reasonable to enforce and implement?)
 - Once such policy is applied, it cannot be modified: removal or modifications are noops; script-inserted policies are ignored?

Others? Is this practical and/or reasonable to implement?

/cc @jpchase @clelland @mkruisselbrink @mikewest

**Comment by michael-oneill** [comment]
Many companies subcontract the development and admin of their sites to agencies, for example a particular multi-national consumer goods manufacturer I work with has many thousands of brand sites administered by disparate agencies in several countries. It is very hard to distribute code or policy to agencies in order to implement policy related response headers, and the CSP meta support allows them to distribute a line of external centrally managed script to dynamically insert a meta http_equiv tag across all their sites.

The Feature-Policy header  would also be very useful to them, but they would need it to be insertable via a meta tag. The script would be executed before any subresources were loaded, and it would be fine if the first instance is not able to be overridden e.g. like the CSP.  An existing header would take precedence, again like the CSP.

**Comment by igrigorik** [comment]
> It is very hard to distribute code or policy to agencies in order to implement policy related response headers, and the CSP meta support allows them to distribute a line of external centrally managed script to dynamically insert a meta http_equiv tag across all their sites.

This is actually quite complicated.. and I'm not sure if it's practical. For one, this assumes that we're toggling interfaces at runtime: we'd have to create the context with everything enabled and then toggle interfaces on/off based on injected <meta>-policy. I'll defer to @clelland on this, but from my current understanding of how we're implementing this, I don't think we can support the "inject policy via tag manager" use case; the policy has to be set before any javascript is run.

**Comment by clelland** [comment]
> the policy has to be set before any javascript is run.

Yes -- implementation-wise, I think it would be hard to support anything else in any kind of rational manner. If we imagine toggling features based on policy injected *after* the JavaScript context has been created, then we need to decide what the behaviour before the <meta> tag is:

If it's off-by-default, then every page, everywhere, has to start out with all feature-policy-features disabled, and we can't enable them until we're sure that no policy will be used. That's a major change to the web platform, and kills legitimate pre-&lt;body&gt; uses of document.write, among other things. It may also interfere with the preload scanner, which is going to want to initiate requests for subresources as early as possible.

If they're on-by-default, and only removed when the policy is seen, then we could end up with situations where the feature is actually used before being disabled, or saved -- scripts might be able to store a reference to things like document.cookie, before they are disabled, and then attempt to use them afterwards. (We might be able to defeat that, by tracing all possible references to the original objects, but I'm not sure that it wouldn't require intrusive changes to V8, and I don't know whether other JS engines would support such a thing)

**Comment by michael-oneill** [comment]
This is already done for CSP implementations (in all major browsers). Firefox (and maybe others) does not stop prefetches to CSP blocked resources, but at least it ensures that blocked script is not executed.

The behaviour before the meta tag is detected should be as it is now, unless there is a pre-existing Feature-Policy header. Of course there would be no guarantees that script loaded after the processing of the meta tag would be affected, and there should be a statement in the rec. pointing that out. 

My other point about inhibiting he processing of embedee  resource Set-Cookies headers might be a bit trickier, but I think should still be possible. For example all Set-Cookies header processing could be delayed till the first script access to document.cookie.

If this (meta tag delivery)  is not supported then there will be a much lower take up of this valuable feature, which would be  a shame.

**Comment by igrigorik** [comment]
> This is already done for CSP implementations (in all major browsers). Firefox (and maybe others) does not stop prefetches to CSP blocked resources, but at least it ensures that blocked script is not executed.

Fetches are much easier in that regard, and even with CSP, the recommended best practices is to deploy it via a header... We shouldn't take on this complexity for v1; there a lot of hidden dragons here.

@michael-oneill note that meta tag support is separate from JS injected support. We *may* be able to support the meta tag, but it would have to come down in the HTML markup and would be subject to a whole lot of other conditions.

**Comment by yoavweiss** [comment]
I concur the need for a way to set this from markup: past polls we ran on the subject as part of the RICG showed that ~25% of devs that answered the poll had no control over their HTTP headers.

I think that limitations such as markup only, before any `<script>` and cannot override header based policies (so can only further restrict them) are reasonable. Cases were the `<meta>` tag doesn't meet such restrictions should result in console errors (and potentially error reports).

@clelland would such limitations ease your concerns about a race between the time the policy is set and scripts using it?

**Comment by michael-oneill** [comment]
A meta tag should not be able to enable a previously disabled feature and the target set of domains should not be able to be made smaller.

**Comment by michael-oneill** [comment]
IMO it would be OK in the first iteration to ignore meta tags if there is a pre-existing FP header

**Comment by yoavweiss** [comment]
How is current spec handling multiple header provided policies?

**Comment by michael-oneill** [comment]
The above link doesn't work, but the W3C version is silent on multiple headers

**Comment by igrigorik** [comment]
Based on an in person chat last week..

- the policy would have be in the `<head>` and must come before any `<link>` and `<script>` elements; otherwise it is ignored (and possibly issue a console warning, or some such).
- if both header + meta policy is present, use same logic as CSP to merge them.

Anything missing?

**Comment by igrigorik** [comment]
@michael-oneill see earlier comment https://github.com/WICG/feature-policy/issues/15#issuecomment-228945994.

**Comment by michael-oneill** [comment]
CSP handles that by only allowing more restrictive policies, e.g. if there is a pre-existing FP header any subsequent meta tag FP is ignored unless it is more restrictive. 

"More restrictive" in this case would mean adding origins to the target set, or replacing "*" with a finite set.

An alternative mechanism (to doing in script) would be syntax to amend the policy directly on particular request header values, like DNT:0 or DNT:1.

**Comment by igrigorik** [comment]
@michael-oneill the existence proof of CSP allowing this is mostly orthogonal, as we're working with difference enforcements constraints and requirements. In particular, we need to set the FP policy (and potentially disable a whole bunch of JS exposed features) when the javascript context is first initialized.

**Comment by justadreamer** [comment]
So this seems to be not implemented for Permissions-Policy.  The spec does not mention meta http-equiv attribute as a way to deliver Permissions-Policy.  Was there an explicit decision to remove this delivery mechanism?
