### ISSUE TITLE
Editorial: please use safelist instead of whitelist

### ISSUE THREAD

**Issue by annevk** [WICG/feature-policy#150]

**Comment by annevk** [comment]
See https://wiki.whatwg.org/wiki/Style#Tone in case you need rationale.

**Comment by jpchase** [comment]
As a coincidence, I was just noticing this in the spec (and the Chromium implementation).

Most of the spec is already using "allowlist", so it might be more consistent to use that instead of "safelist"

**Comment by annevk** [comment]
That's reasonable as well, though I'd somewhat prefer if we used a single generic term across the web platform.

**Comment by clelland** [comment]
There's [a bug](https://crbug.com/822317) to change the class names in the Chromium implementation.

The spec uses 'allowlist' in place of 'whitelist', except in a couple of places. Two are in an example, and can easily be rewritten to use different language:

> ... but enable it for a whitelisted embedee

> The enable policy allows the application to selectively enable such features for whitelisted origins.

The third is using it to describe the way that `<iframe sandbox>` restricts new features by default, and can also be rewritten.

> the sandbox mechanism uses a whitelist approach...

**Comment by jpchase** [comment]
I now see the safelist vs allowlist question was raised in #103.

I agree with the point about using one term consistently. I imagine there was some debate to land on safelist, by persons more experienced in the spec space. To me, "safe" has more specific meaning that "allow". It almost feels like some kind of guarantee.

In any case, PR #151 addresses the main point of this issue - removing the undesirable term. I'll leave it to #103 to resolve which term should be used throughout the spec.
