### ISSUE TITLE
Where is https://github.com/WICG/feature-policy/blob/gh-pages/features.md#sensor-features

### ISSUE THREAD

**Issue by N0ps32** [WICG/feature-policy#183]
Chrome 68 generates this warning in the developer console: 

> target-script-min.js:556 The devicemotion events are blocked by feature policy. See https://github.com/WICG/feature-policy/blob/gh-pages/features.md#sensor-features

You removed this file. Where can I find information to fix my issue now?

**Comment by clelland** [comment]
The file was inadvertently removed from the gh-pages branch; I'm working on getting it back in place because of documentation like that.

For now, you can see the file on the master branch, at https://github.com/WICG/feature-policy/blob/master/features.md#sensor-features

(The only difference in the URL is "gh-pages" is changed to "master")

**Comment by N0ps32** [comment]
Thanks, that solved my issue!

**Comment by Sergio16T** [comment]
Hello! Trying to upload a project to Github with a google 360 virtual tour of business. However the page will not upload to Github project site. It builds fine when I open my file in the browser outside of Github.. even with the above error. I'm guessing the error is why it's not building. 

What do I do to remove error from the console (the features.md#sensor features) 
Not seeing anything on the link describing device orientation blocked.

**Comment by rajktariya** [comment]
its here
https://github.com/w3c/webappsec-feature-policy/blob/master/features.md#sensor-features

**Comment by anveshpuli** [comment]
do we need to add those feature while launch or disable them to fix this issue: VM16 3e532e16d2208ea2cf9e5ae833bede:1 The devicemotion events are blocked by feature policy. See https://github.com/WICG/feature-policy/blob/master/features.md#sensor-features

**Comment by ashishkumar-xx** [comment]
Is there any way to unblock it ?
