### ISSUE TITLE
"companion document" link 404s

### ISSUE THREAD

**Issue by equalsJeffH** [WICG/feature-policy#190]
[companion document](https://github.com/WICG/feature-policy/blob/gh-pages/features.md) in [S 4.1. Policy-controlled Features](https://wicg.github.io/feature-policy/#features) 404s

perhaps https://github.com/WICG/feature-policy/blob/master/features.md is a stable link?

**Comment by clelland** [comment]
Thanks! That's definitely the right link there. I'll fix that right away. I moved the repo source from the gh-pages branch to the master branch, and gh-pages is only used for publishing the rendered spec now, but there are still links out there to the old locations. :(

(That document is also a bit out-of date, but that's a separate issue)
