### ISSUE TITLE
Spec "disable: MIDI" enforcement

### ISSUE THREAD

**Issue by igrigorik** [WICG/feature-policy#2]
Current proposal is to decline the permissions requests ([requestMIDIAccess](http://webaudio.github.io/web-midi-api/#widl-Navigator-requestMIDIAccess-Promise-MIDIAccess--MIDIOptions-options)): 

- Patch the "algorithm to request MIDI access" to check if MIDI is disabled
 - If disabled, "jump to step labeled failure"... Return `DOMException` with .name set to "`SecurityError`".

**Comment by igrigorik** [comment]
Added in https://github.com/WICG/feature-policy/pull/33/commits/0ba445c43726eb461e422fb4111b1d010ea0cd7f.

**Comment by ddorwin** [comment]
Correction: Was added in a1ae5dd79d75fa88c3525e8595ae7723c7b8f1a8.
