### ISSUE TITLE
Container policy doesn't seem to make sense

### ISSUE THREAD

**Issue by bzbarsky** [WICG/feature-policy#227]
Consider this testcase, loaded from `http://siteA.com`:

    <iframe allow="fullscreen http://siteA.com" src="http://siteB.com"></iframe>

Per current spec, the subframe can use fullscreen, which seems wrong.

What happens is much like what https://github.com/WICG/feature-policy/issues/226 describes, except this time when determining the inherited policy there is a container policy.  So we end up in https://wicg.github.io/feature-policy/#define-inherited-policy-in-container which says, in step 4.1:

> If the allowlist for _feature_ in _container policy_ matches _origin_, and _parent_’s inherited policy for _feature_ is "Enabled", return "Enabled". 

The allowlist contains one item: "http://siteA.com".  _origin_ is the origin of the parent document in this case, so the allowlist matches _origin_ and the inherited policy is "Enabled".

I'm pretty sure that's not the intent... @clelland, am I missing something?

@bakulf

**Comment by bzbarsky** [comment]
I agree that  the proposed fix for #226 would change the behavior here, because at that point we would be looking at http://siteB.com.

But then I'm trying to understand the test at https://github.com/web-platform-tests/wpt/blame/6446b4dc89324df48019ef6fa4999595d1f80abf/feature-policy/feature-policy-frame-policy-allowed-for-self.https.sub.html#L41-L43 -- that's a sandboxed iframe, so the comparison in https://wicg.github.io/feature-policy/#define-inherited-policy-in-container step 4.1 should test false (it's comparing an origin derived from the src attribute with the nonce origin of the sandboxed document) and hence fullscreen should not be allowed in there, right?  But this test claims it  should be allowed.

**Comment by bzbarsky** [comment]
> The allowlist in the container policy, by containing "src", should match the opaque origin of the sandboxed document in the frame.

Maybe or maybe not, depending.  If siteA.com has:

    <iframe sandbox="allow-scripts" src="http://siteB.com" allow="fullscreen 'src'">

and then the page inside navigates to http://siteC.com by setting document.location, I would not expect the resulting siteC page to have the "fullscreen" feature enabled.  It wouldn't be enabled if the iframe were _not_  sandboxed, right?

This seems like a pretty basic problem with using origin compares here to implement 'src'....

For extra fun, there's the question of how this should interact with #223 (i.e. sandboxed iframes with srcdoc and allow="fullscreen  'src'").

What does Chrome implement here?  Or does it not pass the test I mention above?

**Comment by clelland** [comment]
Chrome definitely passes that test -- results are at https://wpt.fyi/results/feature-policy/feature-policy-frame-policy-allowed-for-self.https.sub.html?label=experimental (The test relies on the JS interface to see the active policy, so you need to look at the experimental results, but the policy construction is the same in stable Chrome)

I believe that the current implementation uses a special boolean flag on the container policy, something like "matches_opaque_src", which is true if the `'src'` keyword is used and the frame is sandboxed; that was added as a workaround for an issue in Chrome -- it hasn't been possible to send opaque origins across processes in a way that preserved their identity.

`fullscreen *` should work, for sure, regardless of any navigation in the sandboxed frame. That should be identical to the behavior of `<iframe sandbox="allow-scripts" allowfullscreen>`

Regarding navigations to other sites, I think it needs a bit more thought -- going to siteC.com is one thing; navigating within the same sandboxed site (if that is even a thing that makes sense) may be different.

**Comment by bzbarsky** [comment]
Just to be clear, this came up while implementing feature policy in Firefox, where this test failure initially prompted all sorts of crazy workaround hacks until we basically decided that the spec is either confused or doesn't match the test or  both.

I'm a little  surprised that things were shipped with the spec and test in this state.  :(

**Comment by clelland** [comment]
#229 should fix some of this, except for the opaque origin case. I opened #230 to branch that discussion there.

**Comment by clelland** [comment]
Closing this after #229; #230 contains the sandbox issue now.
