### ISSUE TITLE
Remove the entire Integrations section (monkey patch)

### ISSUE THREAD

**Issue by sideshowbarker** [WICG/feature-policy#245]
As far as I can tell, all of the monkey-patching in https://wicg.github.io/feature-policy/#integrations (*“Integration with HTML”*) has already been merged into the HTML spec, in https://github.com/whatwg/html/pull/3287.

So it seems like all of https://wicg.github.io/feature-policy/#integrations *Integration with HTML* could now be removed from the Feature Policy spec.

And further, since that *Integration with HTML* section is the only subsection of the *Integrations* sections, it seems like the entire *Integrations* section could be dropped.

**Comment by clelland** [comment]
I thought I had already made a PR to do this; apparently not, though. Thanks for bringing it up!
