### ISSUE TITLE
Central list of policies

### ISSUE THREAD

**Issue by craigfrancis** [WICG/feature-policy#255]
Can the spec include, or link to a list of policies implemented in browsers?

Checking the source code for Google Chrome:

https://cs.chromium.org/chromium/src/third_party/blink/renderer/core/feature_policy/feature_policy.cc?q=GetDefaultFeatureNameMap&l=252

You get these policies in Chrome Canary 72:

- autoplay
- camera
- encrypted-media
- fullscreen
- geolocation
- microphone
- midi
- speaker
- sync-xhr
- vr

PaymentRequestEnabled:
- payment

PictureInPictureAPIEnabled:
- picture-in-picture

SensorEnabled:
- accelerometer
- ambient-light-sensor
- gyroscope
- magnetometer

WebUSBEnabled:
- usb

ExperimentalProductivityFeaturesEnabled:
- layout-animations, was '[animations](https://chromium.googlesource.com/chromium/src/+/9024e95af4b609ab5ef86b9baca2a25449f3907c)'
- document-write
- document-domain
- unoptimized-images, was '[image-compression](https://chromium.googlesource.com/chromium/src/+/f91910eba0d6f1d81dc2ec39255b5ad348b39dc6)'
- lazyload
- legacy-image-formats
- oversized-images, was '[max-downscaling-image](https://chromium.googlesource.com/chromium/src/+/f91910eba0d6f1d81dc2ec39255b5ad348b39dc6)'
- unsized-media
- vertical-scroll
- sync-script

And we no longer have:
- [cookie](https://chromium.googlesource.com/chromium/src/+/ce77e4b6d9bc40b34aa45e2297495ba4376754b0)
- [domain](https://chromium.googlesource.com/chromium/src/+/ce77e4b6d9bc40b34aa45e2297495ba4376754b0)
- [vibrate](https://chromium.googlesource.com/chromium/src/+/6684fb7780bea4dacdcb12b14a9b56894e07cbfb)

**Comment by annevk** [comment]
This is #244, no?

**Comment by craigfrancis** [comment]
It is, sorry.
