### ISSUE TITLE
Relationship with permissions spec

### ISSUE THREAD

**Issue by benfredwells** [WICG/feature-policy#27]
This (feature policy) spec redefined permissions that are defined in the [permissions api spec](https://github.com/w3c/permissions). Could this spec link to the permission api spec instead, so adding permissions (e.g. bluetooth, contacts, whatever we dream of next) doesn't require both specs to be updated?

**Comment by raymeskhoury** [comment]
I think @jyasskin was thinking about the relationship between the 2 specs somewhat.

**Comment by jyasskin** [comment]
The list of features has to live somewhere, and both specs need to refer to it. It doesn't matter very much which spec it goes in; there will always be some new things that require updating two places.

**Comment by igrigorik** [comment]
Can we close this? It doesn't seem like there is anything actionable here.

**Comment by alvestrand** [comment]
Can't be closed until we have consensus on where the list lives. @foolip may have opinions.

**Comment by foolip** [comment]
*If* a single list makes sense I don't have an opinion about where it lives, as long as it's in an actively maintained spec where getting changes made is easy enough.

https://w3c.github.io/permissions/#permission-registry exists and already claims to be a registry, but https://wicg.github.io/feature-policy/#features has things like `sync-xhr` which aren't and never will be permissions in the user-facing sense.

So concretely, what's to be done? Maybe just make sure there isn't any *accidental* divergence between the lists?

**Comment by igrigorik** [comment]
FWIW, you can see where I'm headed here: https://cdn.rawgit.com/WICG/feature-policy/idl/index.html#features. The list of "features" will be a superset of the keywords covered by `PermissionName` enum... as such, I'm not sure if and how we want coordinate here. 

One route would be for the Permissions spec to link to the relevant keywords in FP?

**Comment by igrigorik** [comment]
@benfredwells @jyasskin we've revamped the proposal in https://github.com/WICG/feature-policy/issues/27 -- ptal and chime in there. Closing this.

**Comment by alvestrand** [comment]
@igrigorik can you give the correct link? #27 is this bug.

**Comment by igrigorik** [comment]
Oops, apologies: https://github.com/WICG/feature-policy/issues/43

**Comment by alvestrand** [comment]
@igrigorik I can't find an explanation of the relationship to the permissions spec in the explainer at https://docs.google.com/document/d/1k0Ua-ZWlM_PsFCFdLMa8kaVTo32PeNZ4G7FFHqpFx4E/edit#heading=h.4yubgixv5l6b - in particular, there is no explicit reference to the permissions spec, so I'm not 100% sure that's what's being referenced in the section on "how are features disabled".
