### ISSUE TITLE
3.2.1 is not a valid example - conflicting with SameSite

### ISSUE THREAD

**Issue by intchloe** [WICG/feature-policy#30]
In §3.2.1 ([cookie](https://wicg.github.io/feature-policy/#cookie)) there's an invalid example: 

> Given the following header:
>Feature-Policy: {"disable":["cookie"]}
**The following JavaScript code will throw a SecurityError exception:**
```
document.cookie = "a=b;Secure;SameSite";
alert(document.cookie);
```

https://tools.ietf.org/html/draft-west-first-party-cookies-07#section-4.1 says:
>If "cookie-av"'s "attribute-value" is not a case-sensitive match for "Strict" or "Lax", ignore the "cookie-av".

`SameSite` is missing an attribute value (`Lax` or `Strict`) and therefore will the cookie not be sat (in browsers with support for SameSite that is). 

My suggestion is that we should have SameSite in cookie examples but we should add an attribute value, such as `Lax`.

**Comment by igrigorik** [comment]
Removed example in https://github.com/WICG/feature-policy/pull/33; closing.
