### ISSUE TITLE
Mailing list information needs updating

### ISSUE THREAD

**Issue by alvestrand** [WICG/feature-policy#31]
From front page:

This document was published by the WICG as an Editor's Draft. If you wish to make comments regarding this document, please send them to @w3.org (subscribe, archives) with [feature-policy] at the start of your email's subject. All comments are welcome.

That won't work - I assume a specific mailing list was intended, but I don't know which.

**Comment by igrigorik** [comment]
Hmm.. that's automatically injected by respec. @marcoscaceres any tips for how to best handle this?

**Comment by marcoscaceres** [comment]
It seems you are missing "[wgPublicList](https://github.com/w3c/respec/wiki/wgPublicList)" in your config. 

However, I should make ReSpec take that out when Editors prefer to have discussions on github.

**Comment by igrigorik** [comment]
Well, also.. there is no public list mailing list for WICG, right? It'd be nice if respec had some special handling for wicg specs.

**Comment by marcoscaceres** [comment]
so, there is a public list (https://lists.w3.org/Archives/Public/public-wicg/), but it's only used for admin purposes. Feel free to list it for now, as at least it addresses the problem. If someone does actually email about the spec, I'll be sure to reroute it back here. 

I'll also make the switch for CG-type specs.
