### ISSUE TITLE
Understand relationship of OriginPolicy with FeaturePolicy/ContentSecurityPolicy

### ISSUE THREAD

**Issue by ojanvafai** [WICG/feature-policy#35]
This is forking the discussion from https://github.com/WICG/feature-policy/issues/16 to focus on the OriginPolicy vs FeaturePolicy side of it.

My mental model on OriginPolicy is a bit different than what @mikewest and @igrigorik were discussing. I was picturing that we'd have FeaturePolicy and ContentSecurityPolicy. OriginPolicy would just be a way to enable either of those at an origin-wide level.

I think it would be really confusing for OriginPolicy to have it's own set of things it can control. How would we decide what makes sense for OriginPolicy vs the others.

Incidentally, the reason FeaturePolicy only allows toggles is because that makes for a simple platform for developers to understand and for browser vendors to implement. The benefits are defeated if we just add another kind of policy that can avoid that. If we were to do that, we may as well just loosen up FeaturePolicy.

ContentSecurityPolicy is a different beast. Where we can it should just control toggles on APIs, but when security is involved, that's not always an option. The benefit of security is such that we're more willing to take on some platform technical complexity. It's hard to make the argument for FeaturePolicy that the benefits are larger than the platform complexity of doing something more nuanced.

**Comment by igrigorik** [comment]
> My mental model on OriginPolicy is a bit different than what @mikewest and @igrigorik were discussing. I was picturing that we'd have FeaturePolicy and ContentSecurityPolicy. OriginPolicy would just be a way to enable either of those at an origin-wide level.

That's still true, sorry I may have confused things in my comment in #16.

Mike mentioned that he was considering pulling CSP-cookies into FP. However, my concern is that [target use cases](https://w3c.github.io/webappsec-csp/cookies/) don't match FP. Specifically, `host` and `secure` modify behavior of how cookies are processed, whereas FP is focused on 'enable/disable' which only works for `none` case in that spec. As such, we *could* pull out `none` case into FP and disable both document.cookie and Set-Cookie processing.. if it makes sense for this functionality to cascade down when disabled -- does it? We should keep the other directives within CSP. Or, we can keep all three in CSP.. arguably, less confusion for developers.

Origin-Policy is mostly orthogonal to all of the above.. If we keep the mechanism in CSP it just provides an origin-wide opt-in mechanism.

**Comment by igrigorik** [comment]
Closing, see https://github.com/WICG/feature-policy/issues/43.
