### ISSUE TITLE
sync-xhr, async attribute "false"

### ISSUE THREAD

**Issue by craigfrancis** [WICG/feature-policy#36]
In section "3.2.9 sync-xhr" it currently says:

"Disables synchronous XMLHttpRequest API: when open() method is called with async argument set to *true*, an InvalidAccessError except will be thrown."

Shouldn't this be "set to false" because this is blocking synchronous requests.

https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/open

**Comment by clelland** [comment]
Yes, looks like this should be `false` in prose, and in the example code.

**Comment by igrigorik** [comment]
Good catch, thanks for the heads up!
