### ISSUE TITLE
What is the purpose of being able to specify the target?

### ISSUE THREAD

**Issue by sebastiannielsen** [WICG/feature-policy#37]
What is the purpose of being able to specify the target/origin the policy should apply to?

I mean, the Origin: header is supplied with each request, thus the web server could supply a dynamic Feature-Policy: that correspond to the server owner's wishes.

So for example, take this example:

SecureCorp Inc. is hosting an application on "https://example.com" and wants to disable WebRTC on its origin but enable it for a whitelisted embedee ("https://other.com"). It can do so by delivering the following HTTP response header to define a feature policy:

SecureCorp Inc. could simply have code like this (pseduocode, but you understand the idea):

```
if (Request.header('Origin').equals("other.com") && Request.IsSecure) {
Response.header("Feature-Policy") = '{"enable":["webrtc"]}';
}
else
{
Response.header("Feature-Policy") = '{"disable":["webrtc"]}';
}
```

I think dumping the "target" feature completely (and encourage web developers to implement it dynamically instead), would actually make the feature more secure, since the server then does not "leak" the security policy for origins unrelated to the request.

**Comment by igrigorik** [comment]
> I mean, the Origin: header is supplied with each request, thus the web server could supply a dynamic Feature-Policy: that correspond to the server owner's wishes.

It's not. Origin header is completely orthogonal to what `target` provides.  Think ~CSP..

Target specifies the policy for the provided origin, as set by the **embedder**. E.g. if the page has an iframe that loads content from foo.com and there is a policy that says that geolocation is disabled for foo.com (as set by the embedder), then this feature will be disabled for that frame.

**Comment by sebastiannielsen** [comment]
aha, so what you mean is that if foo.com embeds content from example.com, foo.com can then specify a policy that forbids geolocation.
(but example.com cannot specify this)

right?
I think that needs to be clarified in the examples, by replacing "SecureCorp inc" with a domain.
