### ISSUE TITLE
eme: Encrypted Media Extensions 

### ISSUE THREAD

**Issue by Adria2** [WICG/feature-policy#40]
I'd like to suggest Encrypted Media Extensions.
My main concern is security / attack surface. The 3rd party plug-ins have to be trusted with parsing and handling user supplied data.
Piece of mind will be asserting that the app, and any of its child scripts, won't be accessing this API at all.

**Comment by ddorwin** [comment]
Yes, EME should be included. See also https://github.com/w3c/encrypted-media/issues/364.

If there is some boilerplate text for checking policies, we can propose a change.

I think this issue should _not_ be vNext. The Feature Policy side is straightforward, the spec is still very early, and including it will help facilitate understanding and discussion.

**Comment by clelland** [comment]
Added to current spec. (Although all features are now in an informative appendix, so this can 
be implemented at any time in the EME spec without affecting Feature Policy).
Removing vNext milestone.

**Comment by ddorwin** [comment]
I see the name is `"eme"`. EME is an informal name for the spec. Does it make sense to use `"encrypted-media"` instead? That is the "spec short name" as well as generally describes the functionality rather than a specific spec (as is the case for other names, such as `"camera"`). I'll also mention this in https://github.com/w3c/encrypted-media/issues/364.

**Comment by ddorwin** [comment]
@clelland, what do you think?

**Comment by clelland** [comment]
Sorry I missed that -- I'm totally fine with "encrypted-media" as a single token. The only hard requirement on a token, I think, is that it does not contain any space characters. That will mean JSON policies like:

    {"encrypted-media": ["https://www.example.com"],
     "fullscreen": ["https://www.example.com"]}

and `iframe` tags like

    <iframe src="https://www.example.com/" allow="encrypted-media fullscreen"></iframe>

I'll update the appendix in the spec to match.

**Comment by LoonyBean** [comment]
https://wicg.github.io/feature-policy/#eme
Should this be updated too?

**Comment by LoonyBean** [comment]
and https://wicg.github.io/feature-policy/#defined-features

But I guess it doesn't really matter, it is just a temporary spec page.
