### ISSUE TITLE
The WebIDL in section 2.4.1 cookie redefines document.cookie

### ISSUE THREAD

**Issue by tobie** [WICG/feature-policy#42]
Title says it all. The following WebIDL redefines `document.cookie` to be something else than it is now.

```webidl
partial interface Document {
    [Feature=cookie]
    attribute USVString cookie;
};
```

I don't think that this is what you want to do (as it would wreck havoc), but I'm not sure either what it is you want to do.

**Comment by annevk** [comment]
I can't find this in the current document.

**Comment by tobie** [comment]
Indeed.
