### ISSUE TITLE
Normatively reference a definition of "origin"

### ISSUE THREAD

**Issue by ddorwin** [WICG/feature-policy#46]
The spec should normatively reference a definition of "origin" where appropriate, especially in the [target member](https://wicg.github.io/feature-policy/#dfn-target-member) definition.

The reference should probably be https://html.spec.whatwg.org/multipage/browsers.html#concept-origin.

**Comment by clelland** [comment]
I've updated the spec to reference the [URL spec](https://url.spec.whatwg.org/#concept-url-origin) (which is the reference I've used elsewhere) in the section defining allowlists.
