### ISSUE TITLE
Delivery section should address new/unrecognized features and directive members

### ISSUE THREAD

**Issue by ddorwin** [WICG/feature-policy#47]
https://wicg.github.io/feature-policy/#feature-policy-http-header-field says:
>When the user agent receives a Feature-Policy header field, it MUST process and enforce the serialized policy as described in 5.1 Integration with HTML.

Related to #44, including the current directive definition text, this section should acknowledge that clients may not recognize all features or directives members and thus may not process or enforce them as the server intends. In other words, while user agents should do the correct thing for their users, there is no mechanism for the server to guarantee that they are being applied. (In a compliant implementation, the feature policy advertised by each fetch could be used to check.)

<br/>"The meta element" section should have similar MUST language and acknowledgement.

**Comment by clelland** [comment]
@ddorwin, does the text in that [update](https://github.com/clelland/feature-policy/commit/057c41daed1bb213a3f3fe7ce7f1c312ced4462d) make sense to you?

The meta element section has been removed from the spec, pending resolving #55
