### ISSUE TITLE
The implications of the default disable/enable policy are unclear

### ISSUE THREAD

**Issue by ddorwin** [WICG/feature-policy#48]
The implications of the default disable/enable policies defined in the [Feature](https://wicg.github.io/feature-policy/#features) sections is unclear. They are set for all features and one can infer the meaning, but I did not see a reference to them in the algorithms or prose. Also, I believe the corresponding table headers should contain the word "Default".

**Comment by clelland** [comment]
@ddorwin -- in the latest spec updates, this has been rewritten substantially. The section https://wicg.github.io/feature-policy/#default-allowlists now explicitly states what the three defined defaults do, and that is linked from each mention in the appendix.

The actual normative definition of the defaults falls out of the algorithms, but I believe that the prose in S4.9 is clear enough to be used by anyone reading the spec to understand. Does it look okay to you?
