### ISSUE TITLE
Spec "disable: webrtc" enforcement

### ISSUE THREAD

**Issue by igrigorik** [WICG/feature-policy#5]
There is a number of different interfaces we need to consider here...

1. Decline [getUserMedia](http://w3c.github.io/mediacapture-main/#dom-mediadevices-getusermedia) permission request: after, or as part of step 4, check if disable webrtc policy is set. If so, return a promise rejected with a DOMException object...
2. Patch [`RTCPeerConnection()` constructor](http://w3c.github.io/webrtc-pc/#rtcpeerconnection-interface) to check if disable webrtc policy is set, and throw a... SecurityError?

... any others?

**Comment by alvestrand** [comment]
This seems to confuse getUserMedia with WebRTC. They are different things.

**Comment by alvestrand** [comment]
@foolip noted that the discussion is taking place.

**Comment by foolip** [comment]
Yeah, I remembered seeing "webrtc" as a category and wondering if it made sense, mentioned it to @alvestrand today, didn't know there was an issue already.

I suspect this is too broad a label, can it be removed in favor of the specific things you want to disable? After all, it's possible to use getUserMedia to take photo of yourself without involving WebRTC at all.

**Comment by foolip** [comment]
I wondered out loud if this issue might have something to do with IP exposure , and @alvestrand pointed me to https://tools.ietf.org/html/draft-ietf-rtcweb-ip-handling-01

If preventing iframes from using those APIs was part of the orignal motivation, figuring out what the minimal surface to block is would be good. To just make the `RTCPeerConnection()` constructor throw might be doing more than you want?

**Comment by igrigorik** [comment]
@alvestrand @foolip see https://github.com/WICG/feature-policy/pull/33/commits/97243cf24f674a311d3b50bfba39306c6b245a2e - does it make sense? Please chime on that commit and/or on https://github.com/WICG/feature-policy/pull/33.

**Comment by alvestrand** [comment]
Sorry for being slow to respond - this looks OK to me. There are other things that might want to go in either category (ORTC new comms features that can be used without PeerConnection, for instance), but let's burn that bridge when we come to it.
