### ISSUE TITLE
Feature vs W3C Process term

### ISSUE THREAD

**Issue by nigelmegitt** [WICG/feature-policy#60]
The [W3C Process](https://www.w3.org/2017/Process-20170301/) uses the word "feature" in a weakly defined way that generally seems to mean "something substantive" in a Recommendation track document - using the name "Feature" here is a clash that needs to be avoided, since the two do not appear to be coincident, or they might be sometimes, but are not necessarily. 

If there is a clash between the two usages it will probably be a lower cost path to change this document than the W3C Process. On the other hand what term to use instead? "Capability" perhaps?

If there is not intended to be a clash then it would be good to clarify that the intention is that the features in the feature policy are exactly those in Recommendations and to delegate definition of those features to the Recommendations where they are defined.

A nice follow-up would be to add or reference the good practice that features should be explicitly named and defined. An example where this is done through a list of feature designators is [TTML1](https://www.w3.org/TR/ttml1/) and [TTML2](https://www.w3.org/TR/ttml2/) which include a language that allows documents to declare which features a processor needs to support in order to process that document, and for processors to declare which features they support.

**Comment by zcorpan** [comment]
https://www.w3.org/2017/Process-20170301/#substantive-change defines "substantive changes" as "Corrections that do not add new features" or "New features". This seems to contradict your claim that it uses "feature" to mean "something substantive".

The describing text for "New features" is

> Changes that add a new functionality, element, etc.

The readme for this repo says

> Examples of features that could be controlled by feature policy include:
>
>* getUserMedia (Camera, Speakers and Microphone)
>* Fullscreen
>* Geolocation
>* MIDI
>* Payments
>* Synchronous XHR
>* Synchronous scripts
>* Vibrate
>* ...

I fail to see how the two are different.

Even if they are indeed subtly different, I do not understand why this would be a problem, and more generally I object to the idea that W3C specs should avoid general terms that happen to be defined in the W3C Process. For example, the term "member" has very different meaning in the W3C Process compared to "member" in WebIDL, and this has not been a problem. W3C Process also defines the term "proxy"...

**Comment by nigelmegitt** [comment]
Hi @zcorpan thanks for the reply. Your references to the Process appear to back up my argument, in my view, not to contradict it! I'm confused about why our views would differ here.

When I raised the issue I did include the possibility that in fact the usages are intended to be the same, and made a proposal for clarification if that is the case.

I agree that there are some terms where the context makes clear that the meaning is completely different, and "member" and "proxy" are good examples. Here though the context does not make that clear at all, and in fact introduces the question, which is why I raised the issue.

I would be happy if the resolution to this issue is:

1. to clarify that features are processor capabilities defined in Recommendations.
2. to delegate the identification/naming of  features to the specifications in which they are defined.

**Comment by zcorpan** [comment]
Your claim

> The W3C Process uses the word "feature" in a weakly defined way that generally seems to mean "something substantive" in a Recommendation track document

W3C Process tasks about features in the context of changes, and says that there are substantive changes that are not new features (point 3). Hence my understanding is that feature is more specific than "something substantive".

**Comment by nigelmegitt** [comment]
OK I agree my definition is imperfect, and it was meant as a shorthand only for the discussion; but then the term is not formally defined as a term in the Process anyway and is a matter of some interpretation.

On the other hand all new features are clearly are substantive even if some substantive changes are not features.

The Feature [section](https://wicg.github.io/feature-policy/#feature) in this document:

> A feature controlled by this framework is an API or behaviour which can be enabled or disabled in a document or web worker by referring to it in a feature policy. 

is possibly more restrictive than it should be but seems like better wording than I thought I read when I posted the issue last night. Sleeping often makes things look better!

There is one issue with this wording: they are not being enabled or disabled _in_ a document but _by_ a document by the use of syntax within that document. In other words, the feature policy specification is not defining what is permitted within a document but what a document can control in the processor.

> Features have a feature name keyword, which is a token used in policy directives, and a default allowlist, which defines whether the feature is available to top-level documents, and how access to that feature is inherited by cross-origin frames.

This begs the question: where are the feature names defined?

> A user agent has a set of supported features, which is the set of features which it allows to be controlled through policies. User agents are not required to support every feature.

I would not limit this specification to user agents per se - it should apply to any processor.

Then, some processors are likely to support features (at least as loosely defined in the Process) that cannot be controlled through policies. Disambiguating these two sets could be done by defining _controllable features_ as a subset of _supported features_ and making this specification about controllable features. This would for me be a resolution (by sidestepping) to the issue originally raised.

**Comment by clelland** [comment]
I agree with @zcorpan that there's no fundamental mismatch between the two uses of the term, but it wasn't my intention to formally define "Feature" such that that definition extends into other standards that haven't been rigorous with their use of the word.

I think it would make sense to use a unique term here -- "Feature Policy-controlled features", and refer to them simply as "features" for short, within this spec. Then other specs can include wording something like

> the fullscreen API is a [Feature Policy-controlled feature](http://wicg.github.io/feature-policy/#features), with the name `fullscreen` and default allowlist of `["self"]`.

and would then go on to define the semantics of disabling.

**Comment by clelland** [comment]
> There is one issue with this wording: they are not being enabled or disabled in a document but by a document by the use of syntax within that document. In other words, the feature policy specification is not defining what is permitted within a document but what a document can control in the processor.

The wording was meant to define the scope at which a feature is controlled -- enabled or disabled, it is scoped to a document, not to an entire page, nor to specific DOM nodes.

It's an unfortunate ambiguity of the English language -- they are enabled (verb) by syntax or headers in the document (or in the document in their parent frame), but the state of the feature is either enabled or disabled (adjective) within the scope of a given document. 

You're right, though, that this spec isn't defining -- only in the appendix, whose text really belongs in the other relevant specs -- what is or is not allowed; it defines a mechanism for specifying what is allowed.

> This begs the question: where are the feature names defined?

Right now, they're all defined in the [appendix](https://wicg.github.io/feature-policy/#defined-features), but the intention is just to keep the appendix as an informative reference to features which are actually defined in other specs. Each of those specs would use some common wording to declare that a given API or behaviour is a feature-policy-controlled-feature.

**Comment by zcorpan** [comment]
> I think it would make sense to use a unique term here -- "Feature Policy-controlled features", and refer to them simply as "features" for short, within this spec.

SGTM.

**Comment by clelland** [comment]
@nigelmegitt, @zcorpan -- you can check out the PR -- I've switched it to "Policy-controlled feature" ("Feature Policy-controlled feature" seems a bit redundant, and hyphenates awkwardly.)

I've updated the wording inside of the spec to use that term, though not in every place, just where it still sounds fairly natural. In other places, I've left the term "feature", but there's a notice near the definition that explains that "feature", in this spec, *means* "policy-controlled feature".
