### ISSUE TITLE
[TAG] Inconsistent granularity

### ISSUE THREAD

**Issue by triblondon** [WICG/feature-policy#70]
[From TAG review](https://github.com/w3ctag/design-reviews/issues/159)

The allow attribute and the HTTP header have very different granularity. While the header takes a list of allowed origins, the attribute's syntax is essentially sugar for featurename:["*"], with no ability to be more granular. We recognise that this is similar to the relationship between the CSP header and the sandbox attribute, but it feels very inconsistent, and a higher than necessary learning curve.

**Comment by clelland** [comment]
It's actually sugar for `featurename:[<origin of src of iframe>]` (except for the legacy interpretation of `allowfullscreen` and `allowpaymentrequest`,) but yes, it's limited syntactic sugar.

For an initial v1 of the spec, we were trying to find the simplest useful thing to ship. We're looking into how to support a more expressive `allow` attribute (the note in https://wicg.github.io/feature-policy/#container-policies mentions that, at least). The hope is that the attribute as specced is straightforward enough to use in practice, and will usually do the right thing.

**Comment by clelland** [comment]
Aligning the header with the `allow` attribute is now being discussed in #78
