### ISSUE TITLE
[TAG] Inconsistency: enable/disable in explainer but spec only provides enable

### ISSUE THREAD

**Issue by slightlyoff** [WICG/feature-policy#72]
[From TAG review](https://github.com/w3ctag/design-reviews/issues/159)

The explainer includes reference to the ability to disable, as well as enable, features, but the current spec appears to only support allowlists.

**Comment by clelland** [comment]
Thanks, @slightlyoff; the explainer was out-of-date. I've updated it to include just the "allow" iframe attribute.
