### ISSUE TITLE
Feature-Policy ∪ Permission Delegation ∪ Origin Trials

### ISSUE THREAD

**Issue by igrigorik** [WICG/feature-policy#9]
From: https://noncombatant.github.io/permission-delegation-api/

> We recommend that UAs only allow permissions to be granted to embedded applications via explicit delegation from the embedding application.
> ...
> A permission, generally, is an affordance in the UA to allow, deny, throttle, or otherwise regulate access to a powerful feature that the user, through the UA, may grant to the web origin. Examples of powerful features include [geolocation-API] and the getUserMedia API from [webrtc].
> ...
> An embedder can delegate permissions it holds to its embedee(s), thus allowing the embedee to use the powerful feature to which the permission grants access. Similarly, an embedder can undelegate (revoke) a permission from an embedee.

The recommendation is to make powerful features mediated by Permissions API (i.e. features that require user permission) disabled by default in nested context's, and require the parent context to explicitly _delegate permission_ to each embedee to (a) enable access to said feature, and (b) pass along the permission held by the embedder to the embedee.

**Functional requirement:** some features are off by default in nested contexts and the parent context should have a mechanism to selectively enable access to such features.

---

## Enable Policy

The `enable policy` allows a developer to turn on certain features for a `Document` or `Worker`. The policy may be set and communicated via the  `Feature-Policy` HTTP Header Field, or via a declarative API.

> Example A: Site A wants to enable Geolocation for all embedees.
>  > 200 OK
>  > Feature-Policy: {enable: ["geolocation"], mode: "cascade"}
>
> Example B: Site B wants to enable a "trials" feature for its origin.
>  > 200 OK
>  > Feature-Policy: {enable: ["opaque-token"]}
> 
> Example C: Site A wants to also enable notifications for particular embedee.
>   `<iframe enable="notifications" src="foo.com"></iframe>`
>   
>   foo.com has access to geolocation (via Example A) and notifications.

### Extensions to the `iframe` element

```idl
partial interface HTMLIFrameElement {
  [PutForwards=value] readonly attribute DOMTokenList enable;
};
```
The `enable` attribute, when specified, enables specified features for the embedee running in the `iframe`. Its value must be an unordered set of unique space-separated tokens that are ASCII case-insensitive, and is processed by the _"parse enable response policy from value"_ algorithm.

#### Parse _enable response policy_ from value
Note: this would be called from "process response policy" which processes `Feature-Policy` header, and "process attribute policy".

Given a list of ASCII case-insensitive tokens, this algorithm returns a list of valid enable features... Rough sketch:

1. Let _enable policy_ be an empty list.
1. For each item in _list_:
  - If item is one of valid [PermissionName enum values](https://w3c.github.io/permissions/#permission-registry):
    - If item was defined via `enable` attribute:
       - Set _target_ to `iframe` element's `src` attribute value.
    - Otherwise, set _target_ to _target mode_'s value if present, and _self_ if missing.
    - Set _mode_ to `enforce`.
    - Set _report to_ to `null`.
  - Otherwise, if the `<insert ref to Origin Trials token processing algorithm>` algorithm returns "Enabled" when executed upon _item_ and the document's global object:
    - Set _target_ to `self`.
    - Set _mode_ to `enforce`.
    - Set _report to_ to `null`.
  - Otherwise, go to the next item in list. 
  - Append _tuple_ to _enable policy_. 
1. Return _enable policy_.

---

There is a bunch more to work through here, but I think the above would, more or less, allow us to merge Permission Delegation and Origin Trials into a single "enable" mechanism? 

- The processing logic for "trials" would live in the Origin Trials spec; we treat it as opaque token.
- The Permission Delegation spec can drop the mechanism for defining which features are enabled and instead inspect the "[Feature Policy List](http://igrigorik.github.io/feature-policy/#dfn-feature-policy-list)" and define the desired behavior(s).

**Comment by ojanvafai** [comment]
I like it. I think we should flip the default for cascading though. cascade should be opt-out.

Also, we need a disable attribute on iframe as well?

**Comment by igrigorik** [comment]
> I like it. I think we should flip the default for cascading though. cascade should be opt-out.

Yep, that's what we have currently: http://igrigorik.github.io/feature-policy/#the-target-member

> Also, we need a disable attribute on iframe as well?

Yep, see: https://github.com/igrigorik/feature-policy/issues/11

**Comment by igrigorik** [comment]
Had an offline chat with @jpchase @clelland @mkruisselbrink today. Quick summary:

1. The rough integration sketch in https://github.com/igrigorik/feature-policy/issues/10#issuecomment-221972005 sounds reasonable. 
 - One concern is lack of `<meta>` support, opened: https://github.com/igrigorik/feature-policy/issues/15.
 - The algorithm that processes tokens probably shouldn't call out to Origin Trials specifically, instead just provide an extension point for other specs to hook into. 
1. We talked about pro's and con's of hiding interfaces/methods vs throwing exceptions. Agreed that it probably makes sense to hide interfaces for cases like "disable webrtc", less clear on "disable document.cookie" and similar... Need to think about it some more.

Overall though, I think we agreed that it makes sense to explore this further. 

Next step: convert https://github.com/igrigorik/feature-policy/issues/10#issuecomment-221972005 into a concrete proposal.

_p.s. @jpchase @clelland @mkruisselbrink please chime in if I'm forgetting anything._

**Comment by raymeskhoury** [comment]
Hmm would safer defaults be for enable features not to cascade but disabled features to cascade?

**Comment by igrigorik** [comment]
Closing this; we broke out the various pieces of https://github.com/WICG/feature-policy/issues/9#issuecomment-222262060 into separate threads.
