### ISSUE TITLE
Require SecurityError to be used for EME

### ISSUE THREAD

**Issue by foolip** [WICG/feature-policy#92]
In https://github.com/w3c/web-platform-tests/pull/7889 a test was added that asserts that requestMediaKeySystemAccess is rejected with a SecurityError when EME is disabled by FP, but this doesn't appear to be defined in either spec:
https://w3c.github.io/encrypted-media/
https://wicg.github.io/feature-policy/

If this is speedily resolved the test can be left as is, otherwise it should be made a [tentative](http://web-platform-tests.org/writing-tests/file-names.html) test in the meantime.

Noticed in https://chromium-review.googlesource.com/c/chromium/src/+/735324

@orphis @raymeskhoury @clelland

**Comment by clelland** [comment]
@foolip -- I've updated the informal list of features in this repo to reflect that change; I'll see if I can write up a PR for EME with a normative change.

**Comment by clelland** [comment]
Ahh, the PR already exists in https://github.com/w3c/encrypted-media/pull/432, (though should be updated with the right DOMException name), but see the comment https://github.com/w3c/encrypted-media/pull/432#issuecomment-338995043 -- this may be a PR for a little while.

Should probably make the tests tentative instead.

**Comment by foolip** [comment]
Thanks @clelland, I've suggested that change in https://chromium-review.googlesource.com/c/chromium/src/+/735324

**Comment by clelland** [comment]
Closing this for now; I don't think there's any more action to be taken in this repo for it. Please reopen if I've forgotten something

**Comment by raymeskhoury** [comment]
@foolip apologies for the confusion - I thought that having the PR there would be good enough to have the tests and didn't know they should be marked tentative. I'll know for the future!

**Comment by raymeskhoury** [comment]
@foolip apologies for the confusion - I thought that having the PR there would be good enough to have the tests and didn't know they should be marked tentative. I'll know for the future!

**Comment by foolip** [comment]
@raymeskhoury, this idea of tentative tests is very new, so it's no surprise that you hadn't heard of it. The guiding principle is simply that wpt should reflect what the specs say, and tentative tests are a way of adding tests before that's true.
