### ISSUE TITLE
Modification of allowlist at runtime

### ISSUE THREAD

**Issue by alexshalamov** [WICG/feature-policy#97]
Specification does not say what happens when `HTMLIFrameElement.allow` is updated at runtime.

This is important to know for e.g., exposing sensor data. If for some reason, iframe's allow attribute is updated dynamically and access to device's sensors is forbidden, iframe should no longer be able to access sensor readings.

Apologies if that was already discussed, could not find in closed or open issues.

Generic Sensor API issue https://github.com/w3c/sensors/issues/133

**Comment by andrey-logvinov** [comment]
The spec says 

> When not empty, the "allow" attribute will result in adding an allowlist for each recognized feature to the frame’s container policy, when it is contructed.

It is indeed not entirely clear when the frame container policy is constructed. If it is constructed when the frame itself is created then changes to the "allow" attribute would have no effect. If it is constructed each time a new Document is loaded in that frame then the changes would be reflected for the next Document in the frame.

Changing feature policy for a given Document on the fly would greatly complicate policy handling, as you cannot for example "un-resolve" an already resolved promise for an API object and need to invent some "no longer allowed" mode for it.

**Comment by clelland** [comment]
> It is indeed not entirely clear when the frame container policy is constructed. If it is constructed when the frame itself is created then changes to the "allow" attribute would have no effect. If it is constructed each time a new Document is loaded in that frame then the changes would be reflected for the next Document in the frame.

It should be constructed when a new document is loaded -- the idea is that it should have the same behavior as the `sandbox` attribute, and affect the frame at the same time.

After that, it should be immutable; we definitely don't want to have policies changing after the document is loaded.

**Comment by alexshalamov** [comment]
@clelland thanks, so, the policy is constructed / updated when document is loaded. Then, it is immutable until document is reloaded.

Thanks for explanation. I got confused by:
> to the frame’s container policy, when it is contructed.

Unclear what is constructed, policy or frame. Also, a small typo :smile:

**Comment by clelland** [comment]
Thanks, @alexshalamov -- I'll see if I can fix that wording (PRs for clarity are absolutely welcomed) -- and I'll fix that typo, too :)
