### ISSUE TITLE
Media

### ISSUE THREAD

**Issue by bonebizz21** [WICG/feature-policy#98]
Mp3 and other audio won't save to SD card and keeps turning into numbers and oh.   Etc

**Comment by clelland** [comment]
If you're having problems with your browser, you will probably want to ask for help on their support forums. This site is for discussion and development of some new browser features.

Chrome: https://productforums.google.com/forum/#!forum/chrome
Edge: http://answers.microsoft.com/en-us/windows/forum/apps_windows_10-msedge
Firefox: https://support.mozilla.org/en-US/kb/get-community-support
Opera: https://forums.opera.com/
Safari: https://support.apple.com/en-ca/safari
